### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by V-PROUD** [caresvn/v-proud.vn#11]
1. Header Kích thước bé -> Như lần trước đẹp hơn
![image](https://user-images.githubusercontent.com/54876569/64234010-9ad38500-cf1f-11e9-9f1b-f0a75a3165b3.png)

2. Chữ: viết thường, bỏ mũi tên sổ xuống 
3. MediaType
Youtube: Dưới 30s có thể auto play được không
Video Upload: possible?
4. Image Grid
- Description: Cố định số dòng hiển thị
5. Partner Carousel : Hình ảnh hiển thị bị bé
6. Về chúng tôi: chưa thấy hiển thị
 I. Giới thiệu công ty
 II. Chính sách bán hàng
 III. Chính sách bảo hành
 IV. Liên hệ

**Comment by khoipro** [comment]
> Image Grid
> Description: Cố định số dòng hiển thị

@V-PROUD phần này sẽ cần tự nhập chữ dài ngắn nhé. Vì nó là custom text hoàn toàn do bên bạn nhập.

**Comment by khoipro** [comment]
> Partner Carousel : Hình ảnh hiển thị bị bé

Đã fix.

![Screenshot at Sep 06 00-43-57](https://user-images.githubusercontent.com/10395311/64365973-71117f80-d03f-11e9-8fd5-34de2ac4be59.png)

**Comment by khoipro** [comment]
> Chữ: viết thường, bỏ mũi tên sổ xuống

Đã fix.

![Screenshot at Sep 06 00-50-56](https://user-images.githubusercontent.com/10395311/64366437-6c999680-d040-11e9-87ea-0202058f037e.png)

**Comment by khoipro** [comment]
> Youtube: Dưới 30s có thể auto play được không

@V-PROUD 

Phần này không làm vì nhiều trình duyệt họ tắt chế độ auto play với youtube. Quá trình fix sẽ phức tạp dễ dẫn đến cháy deadline.
Thêm nữa trên điện thoại thì không auto play được.

**Comment by khoipro** [comment]
> Video Upload: possible?

Đã đẩy bản cập nhật lên cho riêng video mp4 @V-PROUD 

Video Test MP4 (tải về xong upload lên: http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4)

Khi chuyển tới slide nào có video thì sẽ chạy.

Nếu slide đầu tiên thì sẽ auto play.

![Screenshot at Sep 06 01-22-30](https://user-images.githubusercontent.com/10395311/64368979-90aba680-d045-11e9-8266-4cc2cc180587.png)

**Comment by V-PROUD** [comment]
> > Video Upload: possible?
> 
> Đã đẩy bản cập nhật lên cho riêng video mp4 @V-PROUD
> 
> Video Test MP4 (tải về xong upload lên: http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4)
> 
> Khi chuyển tới slide nào có video thì sẽ chạy.
> 
> Nếu slide đầu tiên thì sẽ auto play.
> 
> ![Screenshot at Sep 06 01-22-30](https://user-images.githubusercontent.com/10395311/64368979-90aba680-d045-11e9-8266-4cc2cc180587.png)

Add phần này vào Wiki giúp tớ nhé
