### ISSUE TITLE
Product Category & Product Single

### ISSUE THREAD

**Issue by V-PROUD** [caresvn/v-proud.vn#13]
Products
1. Danh mục con -> có thể bỏ được không
2. Lớp 2: http://vproud.staging.cares.vn/product_category/3d-coordinates-measuring-machines/
-> Bỏ Banner trên cùng
3. Lớp 3: http://vproud.staging.cares.vn/product_category/hardness-measuring-machines/
![image](https://user-images.githubusercontent.com/54876569/64226887-6c4baf00-cf0b-11e9-8094-ce27df61d23a.png)
-> Thêm cột
3. Lớp 4: Để giống lớp 3
![image](https://user-images.githubusercontent.com/54876569/64226613-4e317f00-cf0a-11e9-9c08-49c62556a60a.png)
4. Lớp lõi Thêm 2 dòng chạy song song khi kéo xuống 
Cần tư vấn thêm -> Link ra Liên hệ
Chọn chi tiết sản phẩm -> Link ra web TMĐT
- Dưới tên sản phẩm: Link hướng dẫn lựa chọn thiết bị

http://vproud.staging.cares.vn/product/sbrv-100d-digital-multifunction-hardness-tester/
Product Details: Thêm Mục Download Catalogue Sản phẩm

**Comment by khoipro** [comment]
> Lớp 4: Để giống lớp 3

@V-PROUD  Cái này có trong từng module, mà đây không phải lớp 4 mà vẫn là lớp 3 thôi. Chỉ là module như ở trên cần phải thêm vào (mình làm demo nên mình không thêm TẤT CẢ).

Về cơ bản:

- Category chủ yếu gồm 3 lớp thôi:

Lớp 1: `http://vproud.staging.cares.vn/san-pham/` (trang chứa toàn bộ Category product)

Lớp 2: `http://vproud.staging.cares.vn/product_category/hardness-measuring-machines/` (category product ngoài cùng, bên trong chỉ chứa các sub-category con).

Lớp 3: `http://vproud.staging.cares.vn/product_category/hardness-measuring-machines/rockwell-hardness-tester/` (category không có category con, chỉ chứa product)

Lớp 4 (chính là product): `http://vproud.staging.cares.vn/product/sbrv-100d-digital-multifunction-hardness-tester/`

Bên bạn có một số comment về thiếu module thì thực ra là do demo link đó không có thêm vào chứ các demo ở #10  mới là đúng nhất.

**Comment by khoipro** [comment]
> Danh mục con -> có thể bỏ được không

@V-PROUD  Mục này trong khi sửa trang thì có thể tắt/bật: http://vproud.staging.cares.vn/wp-admin/post.php?post=67&action=edit&lang=vi

![Screenshot at Sep 05 14-03-23](https://user-images.githubusercontent.com/10395311/64319206-fbc59080-cfe5-11e9-985a-6c516676e28f.png)

**Comment by khoipro** [comment]
> Lớp 2: http://vproud.staging.cares.vn/product_category/3d-coordinates-measuring-machines/
-> Bỏ Banner trên cùng

Mục này trong khi sửa Product Category có thể xóa đi: http://vproud.staging.cares.vn/wp-admin/term.php?taxonomy=product_category&tag_ID=11&post_type=product&wp_http_referer=%2Fwp-admin%2Fedit-tags.php%3Ftaxonomy%3Dproduct_category%26post_type%3Dproduct

![Screenshot at Sep 05 14-05-51](https://user-images.githubusercontent.com/10395311/64319329-4810d080-cfe6-11e9-92b4-262a2821227b.png)

**Comment by khoipro** [comment]
> Lớp 3: http://vproud.staging.cares.vn/product_category/hardness-measuring-machines/ -> Thêm cột

@V-PROUD  Cái này đang ngang hàng (cùng là lớp 2 chứ không phải lớp 3) với cái `http://vproud.staging.cares.vn/product_category/3d-coordinates-measuring-machines/` nên mình không rõ là thêm mấy cột là chuẩn, cần xác nhận lại. Vì một khi áp dụng thì các product category đều sẽ áp dụng giống nhau.

NGANG HÀNG:

```
http://vproud.staging.cares.vn/product_category/hardness-measuring-machines/
http://vproud.staging.cares.vn/product_category/3d-coordinates-measuring-machines/
```

**Comment by khoipro** [comment]
> Dưới tên sản phẩm: Link hướng dẫn lựa chọn thiết bị

@V-PROUD bạn có demo ở đâu như vậy không? Nếu không có thì rất khó để làm vì không hiểu ý tưởng này.

**Comment by khoipro** [comment]
> http://vproud.staging.cares.vn/product/sbrv-100d-digital-multifunction-hardness-tester/ => Product Details: Thêm Mục Download Catalogue Sản phẩm

Phần này có thể tự thêm/bớt chứ không fix cứng nhé @V-PROUD 

http://vproud.staging.cares.vn/wp-admin/post.php?post=116&action=edit&lang=vi

![Screenshot at Sep 05 14-12-54](https://user-images.githubusercontent.com/10395311/64319753-501d4000-cfe7-11e9-8ead-c8cff86961e6.png)

**Comment by khoipro** [comment]
> Lớp lõi Thêm 2 dòng chạy song song khi kéo xuống
> Cần tư vấn thêm -> Link ra Liên hệ
> Chọn chi tiết sản phẩm -> Link ra web TMĐT
> Dưới tên sản phẩm: Link hướng dẫn lựa chọn thiết bị

Layout này mình nghĩ là hợp lý, vì phần scroll kéo xuống nó chạy theo đối với website dạng thông tin như thế này là không cần thiết.

![Screenshot at Sep 10 07-25-03](https://user-images.githubusercontent.com/10395311/64575049-1dcf6200-d39c-11e9-987b-d9a607b3d55a.png)

**Comment by V-PROUD** [comment]
![image](https://user-images.githubusercontent.com/54876569/66545705-7e051f80-eb65-11e9-865f-f074fcb58a01.png)
 khi nội dung dài quá thì bố cục mất cân đối -> có cách nào khắc phục ko
tớ không thấy chức năng căn lề chữ đều hai bên

**Comment by khoipro** [comment]
Bạn phải chia nhỏ thành các mục đẩy xuống đây chứ ở trên chỉ là 1 đoạn intro về sản phẩm ngắn thôi.

<img width="800" alt="Screenshot at Oct 11 06-48-40" src="https://user-images.githubusercontent.com/10395311/66614428-3d53e780-ebf3-11e9-899a-9d87a8540658.png">

**Comment by khoipro** [comment]
Bạn cần phải set ảnh cho nó thì mới hiện ở bên phải nhé @V-PROUD 

<img width="317" alt="Screenshot at Oct 11 06-49-33" src="https://user-images.githubusercontent.com/10395311/66614458-5492d500-ebf3-11e9-8976-0b1ffce4442b.png">

**Comment by khoipro** [comment]
Tất cả tên sản phẩm nên viết thường để tránh lỗi không nhất quán sau này.

<img width="808" alt="Screenshot at Oct 11 06-50-40" src="https://user-images.githubusercontent.com/10395311/66614488-72f8d080-ebf3-11e9-875d-5d37c3e004fb.png">

**Comment by khoipro** [comment]
Khi lựa chọn danh mục, chỉ cần chọn cái gần nhất của nó thôi, đừng chọn cả bộ sẽ hiển thị cấu trúc sai.

<img width="305" alt="Screenshot at Oct 11 06-51-33" src="https://user-images.githubusercontent.com/10395311/66614531-a176ab80-ebf3-11e9-9009-19c907942cf0.png">
