### ISSUE TITLE
Single Product > Accordion

### ISSUE THREAD

**Issue by khoipro** [caresvn/v-proud.vn#16]
![Screenshot at Sep 05 14-22-58](https://user-images.githubusercontent.com/10395311/64320422-b35ba200-cfe8-11e9-8b20-44dc557bf6f4.png)

Missing color or text line for color.

**Comment by V-PROUD** [comment]
phần này yêu cầu người dùng điền email để gửi catalogue về mail
1. nếu  được sẽ dùng email MKT tự động để gửi catalogue
2. nếu không tự động thì yêu cầu người dùng ghi số điện thoại

**Comment by khoipro** [comment]
> phần này yêu cầu người dùng điền email để gửi catalogue về mail

Đã dựng form hiển thị lên @V-PROUD

![Screenshot at Sep 10 06-41-35](https://user-images.githubusercontent.com/10395311/64573715-87e50880-d396-11e9-8e1a-b12123d762c2.png)

Cấu hình: http://vproud.staging.cares.vn/wp-admin/admin.php?page=acf-options-page-settings 

Bao gồm các mục sau:

- Form ID (lấy từ link  http://vproud.staging.cares.vn/wp-admin/admin.php?page=gf_edit_forms)
- Title (nền màu xanh, là phần text "Download Brochure")
- Description (phần text "Get a free brochure to your email.")

Sửa nội dung các field (như Họ tên,...): http://vproud.staging.cares.vn/wp-admin/admin.php?page=gf_edit_forms

Lưu ý: Form này muốn nhận email marketing tự động thì phải cấu hình bên hệ thống email marketing (thường trả phí). Đây là chi phí nằm ngoài báo giá thiết kế website.

Mình đang tạm thời cài dịch vụ tích hợp với https://www.cleverreach.com/en/pricing/ (cho phép quản lý danh sách tối đa 250 contacts, và gửi tối đa 1000 email/tháng).

![Screenshot at Sep 10 06-48-34](https://user-images.githubusercontent.com/10395311/64573844-06da4100-d397-11e9-8d69-5db71ae0fb53.png)

Giá đầy đủ: https://www.cleverreach.com/en/pricing/

Việc bạn lựa chọn dịch vụ email marketing nào và chi phí bao nhiêu bên mình có thể cùng tham khảo, nhưng việc tích hợp nó vào hệ thống website là không miễn phí nhé, trừ trường hợp bạn đăng ký dịch vụ email marketing nằm trong danh sách được hỗ trợ: https://www.gravityforms.com/add-ons/
