### ISSUE TITLE
Phân quyền User

### ISSUE THREAD

**Issue by V-PROUD** [caresvn/v-proud.vn#17]
Quyền của từng phần này như nào, một user có được phân trên 1 quyền ko
![image](https://user-images.githubusercontent.com/54876569/65958414-88466000-e479-11e9-96fa-77d375fca7e3.png)

**Comment by khoipro** [comment]
@V-PROUD quyền user có thể xem tham khảo ở đây nhé:

https://themeisle.com/blog/wordpress-user-roles/

**Comment by khoipro** [comment]
@V-PROUD mỗi user chỉ có một quyền thôi, và nó tương ứng với cấp độ như link tớ mô tả.
