### ISSUE TITLE
Category

### ISSUE THREAD

**Issue by V-PROUD** [caresvn/v-proud.vn#23]
![image](https://user-images.githubusercontent.com/54876569/66672882-8eaeb600-ec89-11e9-8fc9-8390bcf8c1c5.png)
Làm sao để biết category lớp 1, 2 ,3

**Comment by khoipro** [comment]
Lớp 1 (nó là trang Products - và chỉ có duy nhất 1 thôi, sửa ở bên Page)
Lớp 2 (các danh mục mà chỉ chứa danh mục con, không phải danh mục CUỐI) => riêng lớp này có thể có 2-3 lớp mà cứ không phải cuối thì tự nó chỉ là lớp 2 thôi.
Lớp 3 (các danh mục nhỏ nhất, chứa sản phẩm bên trong)
