### ISSUE TITLE
Brochure Download

### ISSUE THREAD

**Issue by V-PROUD** [caresvn/v-proud.vn#24]
![image](https://user-images.githubusercontent.com/54876569/66673016-e77e4e80-ec89-11e9-8edf-2aafc2b51db7.png)
 
http://vproud.staging.cares.vn/wp-admin/post.php?lang=en&action=edit&post_type=product&post=256

-> T tìm để sửa cái phần nội dung tải brochure mà không thấy, mục này có để mặc định ở tất cả các sản phẩm được k

**Comment by khoipro** [comment]
Chuyển vào hệ thống mới.
