### ISSUE TITLE
Main Menu

### ISSUE THREAD

**Issue by khoipro** [caresvn/v-proud.vn#9]
### Design

**Desktop**

<img width="1203" alt="Screenshot at Sep 02 17-23-41" src="https://user-images.githubusercontent.com/10395311/64108209-76a06880-cda6-11e9-9eec-26d9424de794.png">

**Mobile**

<img width="483" alt="Screenshot at Sep 02 17-23-52" src="https://user-images.githubusercontent.com/10395311/64108227-815afd80-cda6-11e9-886c-dfe30305f702.png">

**Mobile Menu - khi mở**

<img width="746" alt="Screenshot at Sep 02 17-24-58" src="https://user-images.githubusercontent.com/10395311/64108272-9b94db80-cda6-11e9-92d1-e44181b80d7c.png">

### Vị trí cấu hình menu

<img width="160" alt="menu-location" src="https://user-images.githubusercontent.com/10395311/64107882-ac911d00-cda5-11e9-8a97-c0a9ee673e42.png">

### Dịch menu tương đương sang ngôn ngữ khác

<img width="1267" alt="menu-translation" src="https://user-images.githubusercontent.com/10395311/64107896-b9157580-cda5-11e9-8c79-e319e61a36df.png">

### Menu dạng Mega-menu

**Hiển thị:**

<img width="926" alt="menu-megamenu" src="https://user-images.githubusercontent.com/10395311/64107979-e6622380-cda5-11e9-8471-cb1d68e223f4.png">

**Cấu hình:**

<img width="468" alt="menu-megamenu-setup" src="https://user-images.githubusercontent.com/10395311/64108016-f7129980-cda5-11e9-9b27-4121c6335858.png">

### Menu dạng dropdown

**Hiển thị:**

<img width="219" alt="Screenshot at Sep 02 17-21-20" src="https://user-images.githubusercontent.com/10395311/64108075-19a4b280-cda6-11e9-9d8c-b1cad7d2a97a.png">

**Cấu hình:**

Chỉ cần xếp thứ tự chồng lên nhau. Không tick các mục như bên Mega Menu.

<img width="472" alt="Screenshot at Sep 02 17-21-09" src="https://user-images.githubusercontent.com/10395311/64108096-2c1eec00-cda6-11e9-811b-34b966c523cb.png">

**Comment by V-PROUD** [comment]
Link Youtube dưới 30s mới có thể chạy trên banner?

**Comment by khoipro** [comment]
> Link Youtube dưới 30s mới có thể chạy trên banner?

Theo như hướng dẫn ở đây thì có thể: https://appuals.com/autoplay-embedded-youtube-videos-page/

Tuy nhiên cần test trong tình huống slider (vì có nhiều video, nếu nó autoplay thì có thể dẫn đến chạy nhiều video một lúc)

**Comment by khoipro** [comment]
Chuyển vào trong wiki https://github.com/caresvn/v-proud.vn/wiki/Header
